# 11_reo_glmnet_qc.R - REO Panel Phase 1: Sample QC with glmnet
# Purpose: Remove R0-like samples from R1 using L1-regularized logistic regression
# Input: thyr_deg_results.rds, analysis_dgelist_R0_vs_R1_tumor.rds, case master
# Output: reo_glmnet_qc_results.rds
# Version: v1.0
# Date: 2025-12-05
# Reference: REO_Panel_Protocol_v2.md

source("analysis_v7/setup.R")

cat("\n")
cat("=======================================================================\n")
cat("  REO Panel Phase 1: Sample QC with glmnet\n")
cat("=======================================================================\n")
cat("Date:", as.character(Sys.Date()), "\n")
cat("Purpose: Remove R0-like samples from R1 group\n")
cat("Method: L1-regularized logistic regression (Lasso)\n\n")

# ============================================================================
# Load packages
# ============================================================================

suppressPackageStartupMessages({
  library(edgeR)
  library(glmnet)
  library(dplyr)
})

# ============================================================================
# Configuration
# ============================================================================

CONFIG <- list(
  # glmnet parameters
  GLMNET_ALPHA = 1,              # Lasso (L1 regularization)
  GLMNET_NFOLDS = 5,             # Cross-validation folds
  GLMNET_LAMBDA = "lambda.1se",  # Conservative lambda selection
  
  
  # R0-like threshold
  R0LIKE_QUANTILE = 0.25,        # 25th percentile of R0's P_hat
  
  # Random seed
  SEED = 1986,
  
  # Output control
  VERBOSE = TRUE
)

cat("Configuration:\n")
cat("  glmnet alpha:", CONFIG$GLMNET_ALPHA, "(Lasso)\n")
cat("  CV folds:", CONFIG$GLMNET_NFOLDS, "\n")
cat("  Lambda selection:", CONFIG$GLMNET_LAMBDA, "\n")
cat("  R0-like threshold: R0", sprintf("%.0f%%", CONFIG$R0LIKE_QUANTILE * 100), "percentile\n")
cat("  Random seed:", CONFIG$SEED, "\n")

set.seed(CONFIG$SEED)

# ============================================================================
# 1. Load required data
# ============================================================================

cat("\n--- 1. Loading required data ---\n")

# 1.1 Load DEG results
deg_results_path <- paste0(paths$processed, "thyr_deg_results.rds")
if (!file.exists(deg_results_path)) {
  stop("ERROR: thyr_deg_results.rds not found. Run 09_deg_analysis.R first.")
}

deg_output <- readRDS(deg_results_path)
cat("  DEG results loaded\n")

# Extract R0_vs_R1_tumor results
r0r1_results <- deg_output$deg_results$R0_vs_R1_tumor
if (is.null(r0r1_results)) {
  stop("ERROR: R0_vs_R1_tumor results not found in DEG output.")
}

deg_df <- r0r1_results$deg_summary$results_df
cat(sprintf("  Total genes in DEG results: %d\n", nrow(deg_df)))

# Get significant DEGs
sig_degs <- deg_df[deg_df$significant == TRUE, ]
cat(sprintf("  Significant DEGs: %d\n", nrow(sig_degs)))
cat(sprintf("    UP (R1 > R0): %d\n", sum(sig_degs$log2FC > 0)))
cat(sprintf("    DOWN (R1 < R0): %d\n", sum(sig_degs$log2FC < 0)))

# 1.2 Load DGEList (DEGES-normalized)
dgelist_path <- paste0(paths$processed, "analysis_dgelist_R0_vs_R1_tumor.rds")
if (!file.exists(dgelist_path)) {
  stop("ERROR: analysis_dgelist_R0_vs_R1_tumor.rds not found. Run 08_deges_normalization.R first.")
}

dgelist <- readRDS(dgelist_path)
cat(sprintf("  DGEList loaded: %d genes × %d samples\n", 
            nrow(dgelist), ncol(dgelist)))

# 1.3 Load case master
case_master_path <- paste0(paths$processed, "thyr_case_master_stage2_filtered.rds")
if (!file.exists(case_master_path)) {
  stop("ERROR: Case master not found. Run 06_purity_analysis.R first.")
}

case_master <- readRDS(case_master_path)
cat(sprintf("  Case master loaded: %d cases\n", nrow(case_master)))

# ============================================================================
# 2. Identify RET fusion samples
# ============================================================================

cat("\n--- 2. Identifying RET fusion samples ---\n")

# Load pre-computed sample lists (generated by 08_deges_normalization.R)
sample_lists_path <- paste0(paths$processed, "analysis_sample_lists.rds")

if (!file.exists(sample_lists_path)) {
  stop("ERROR: analysis_sample_lists.rds not found. Run 08_deges_normalization.R first.")
}

sample_lists <- readRDS(sample_lists_path)
cat("  Pre-computed sample lists loaded\n")

# Get RET group tumor samples
r0_tumor_ids <- sample_lists$R0$tumor
r1_tumor_ids <- sample_lists$R1$tumor

cat(sprintf("  R0 tumor samples: %d\n", length(r0_tumor_ids)))
cat(sprintf("  R1 tumor samples: %d\n", length(r1_tumor_ids)))

# Verify samples exist in DGEList
available_samples <- colnames(dgelist)
r0_in_dgelist <- r0_tumor_ids %in% available_samples
r1_in_dgelist <- r1_tumor_ids %in% available_samples

cat(sprintf("  R0 in DGEList: %d / %d\n", sum(r0_in_dgelist), length(r0_tumor_ids)))
cat(sprintf("  R1 in DGEList: %d / %d\n", sum(r1_in_dgelist), length(r1_tumor_ids)))

r0_tumor_ids <- r0_tumor_ids[r0_in_dgelist]
r1_tumor_ids <- r1_tumor_ids[r1_in_dgelist]

if (length(r0_tumor_ids) < 5 || length(r1_tumor_ids) < 5) {
  stop("ERROR: Insufficient samples for glmnet QC.")
}

# Load ret_cases for POC info
ret_cases <- case_master %>%
  filter(driver == "RET" & 
           has_outlier_tumor == 0 & 
           has_outlier_normal == 0 & 
           low_purity == 0)

# Load sample metadata for case_submitter_id mapping
se_path <- paste0(paths$processed, "thyr_se_strand2_nonzero.rds")
if (file.exists(se_path)) {
  suppressPackageStartupMessages(library(SummarizedExperiment))
  se <- readRDS(se_path)
  sample_metadata <- as.data.frame(colData(se))
  cat("  Sample metadata loaded for case ID mapping\n")
} else {
  sample_metadata <- NULL
  cat("  Warning: Sample metadata not found, POC info will be unavailable\n")
}

# ============================================================================
# 3. Prepare expression matrix for glmnet
# ============================================================================

cat("\n--- 3. Preparing expression matrix ---\n")

# Get logCPM values
all_sample_ids <- c(r0_tumor_ids, r1_tumor_ids)
logcpm <- cpm(dgelist[, all_sample_ids], log = TRUE, prior.count = 1)

cat(sprintf("  logCPM matrix: %d genes × %d samples\n", 
            nrow(logcpm), ncol(logcpm)))

# Filter to DEGs only
deg_gene_ids <- sig_degs$gene_id
common_genes <- intersect(deg_gene_ids, rownames(logcpm))

cat(sprintf("  DEGs available in expression matrix: %d\n", length(common_genes)))

if (length(common_genes) < 50) {
  warning("WARNING: Less than 50 DEGs available. glmnet may be unstable.")
}

# Subset to DEGs
logcpm_deg <- logcpm[common_genes, ]

# Get PI for sign alignment
# PI > 0.5 means R1 > R0, PI < 0.5 means R1 < R0
deg_info <- sig_degs[match(common_genes, sig_degs$gene_id), ]

if (!"PI" %in% colnames(deg_info)) {
  stop("ERROR: PI column not found in DEG results. Ensure 09_deg_analysis.R v7.4+ was used.")
}

pi_signs <- sign(deg_info$PI - 0.5)

cat(sprintf("  Genes with PI > 0.5 (R1 > R0): %d\n", sum(pi_signs > 0)))
cat(sprintf("  Genes with PI < 0.5 (R1 < R0): %d\n", sum(pi_signs < 0)))
cat(sprintf("  Genes with PI = 0.5 (no difference): %d\n", sum(pi_signs == 0)))

# ============================================================================
# 4. Apply sign alignment
# ============================================================================

cat("\n--- 4. Applying sign alignment ---\n")

# z_ig = sign(PI_g - 0.5) × logCPM_ig
# This makes larger z values indicate "more R1-like"
z_matrix <- sweep(logcpm_deg, 1, pi_signs, "*")

cat("  Sign alignment applied (using PI)\n")
cat("  Interpretation: Higher z values = more R1-like expression pattern\n")

# Transpose for glmnet (samples × genes)
X <- t(z_matrix)

# Create response vector (R0 = 0, R1 = 1)
y <- c(rep(0, length(r0_tumor_ids)), rep(1, length(r1_tumor_ids)))
names(y) <- c(r0_tumor_ids, r1_tumor_ids)

cat(sprintf("  Design matrix X: %d samples × %d features\n", nrow(X), ncol(X)))
cat(sprintf("  Response y: %d R0, %d R1\n", sum(y == 0), sum(y == 1)))

# ============================================================================
# 5. Run glmnet with cross-validation
# ============================================================================

cat("\n--- 5. Running glmnet ---\n")

# Run cross-validated glmnet
set.seed(CONFIG$SEED)
cv_fit <- cv.glmnet(
  x = X,
  y = y,
  family = "binomial",
  alpha = CONFIG$GLMNET_ALPHA,
  nfolds = CONFIG$GLMNET_NFOLDS,
  type.measure = "deviance"
)

cat(sprintf("  Lambda range: %.4f to %.4f\n", min(cv_fit$lambda), max(cv_fit$lambda)))
cat(sprintf("  Lambda.min: %.4f (minimum CV error)\n", cv_fit$lambda.min))
cat(sprintf("  Lambda.1se: %.4f (conservative)\n", cv_fit$lambda.1se))

# Select lambda
if (CONFIG$GLMNET_LAMBDA == "lambda.1se") {
  selected_lambda <- cv_fit$lambda.1se
} else {
  selected_lambda <- cv_fit$lambda.min
}

cat(sprintf("  Selected lambda: %.4f (%s)\n", selected_lambda, CONFIG$GLMNET_LAMBDA))

# Get coefficients at selected lambda
coef_sparse <- coef(cv_fit, s = selected_lambda)
nonzero_coef <- sum(coef_sparse[-1, 1] != 0)  # Exclude intercept

cat(sprintf("  Non-zero coefficients: %d / %d genes\n", nonzero_coef, ncol(X)))

# ============================================================================
# 6. Calculate P_hat (probability of being R1)
# ============================================================================

cat("\n--- 6. Calculating P_hat (R1 probability) ---\n")

# Predict probabilities for all samples
p_hat <- predict(cv_fit, newx = X, s = selected_lambda, type = "response")[, 1]
names(p_hat) <- rownames(X)

# Separate by group
p_hat_r0 <- p_hat[r0_tumor_ids]
p_hat_r1 <- p_hat[r1_tumor_ids]

cat("  P_hat distribution for R0 (should be low):\n")
cat(sprintf("    Min: %.3f, Q1: %.3f, Median: %.3f, Q3: %.3f, Max: %.3f\n",
            min(p_hat_r0), quantile(p_hat_r0, 0.25), median(p_hat_r0),
            quantile(p_hat_r0, 0.75), max(p_hat_r0)))

cat("  P_hat distribution for R1 (should be high):\n")
cat(sprintf("    Min: %.3f, Q1: %.3f, Median: %.3f, Q3: %.3f, Max: %.3f\n",
            min(p_hat_r1), quantile(p_hat_r1, 0.25), median(p_hat_r1),
            quantile(p_hat_r1, 0.75), max(p_hat_r1)))

# ============================================================================
# 7. Identify R0-like samples in R1
# ============================================================================

cat("\n--- 7. Identifying R0-like samples ---\n")

# Set threshold as R0's 25th percentile
theta <- quantile(p_hat_r0, CONFIG$R0LIKE_QUANTILE)
cat(sprintf("  Threshold (R0 %.0f%% percentile): %.3f\n", 
            CONFIG$R0LIKE_QUANTILE * 100, theta))

# Identify R0-like samples in R1
r0_like_mask <- p_hat_r1 <= theta
r0_like_ids <- names(p_hat_r1)[r0_like_mask]
retained_r1_ids <- names(p_hat_r1)[!r0_like_mask]

cat(sprintf("\n  R1 samples classified as R0-like: %d\n", length(r0_like_ids)))
cat(sprintf("  R1 samples retained: %d\n", length(retained_r1_ids)))

# Helper function to get POC for a sample
get_poc <- function(sid, sample_metadata, ret_cases) {
  if (is.null(sample_metadata)) return(NA_real_)
  case_id <- sample_metadata$case_submitter_id[sample_metadata$sample_submitter_id == sid]
  if (length(case_id) == 0) return(NA_real_)
  poc <- ret_cases$POC[ret_cases$case_submitter_id == case_id[1]]
  if (length(poc) == 0) return(NA_real_)
  return(poc[1])
}

if (length(r0_like_ids) > 0) {
  cat("\n  R0-like samples (excluded):\n")
  for (sid in r0_like_ids) {
    poc <- get_poc(sid, sample_metadata, ret_cases)
    if (!is.na(poc)) {
      cat(sprintf("    %s: P_hat=%.3f, POC=%.1f%%\n", sid, p_hat_r1[sid], poc))
    } else {
      cat(sprintf("    %s: P_hat=%.3f\n", sid, p_hat_r1[sid]))
    }
  }
}

cat("\n  Retained R1 samples:\n")
for (sid in retained_r1_ids) {
  poc <- get_poc(sid, sample_metadata, ret_cases)
  if (!is.na(poc)) {
    cat(sprintf("    %s: P_hat=%.3f, POC=%.1f%%\n", sid, p_hat_r1[sid], poc))
  } else {
    cat(sprintf("    %s: P_hat=%.3f\n", sid, p_hat_r1[sid]))
  }
}

# ============================================================================
# 8. Compile results
# ============================================================================

cat("\n--- 8. Compiling results ---\n")

# Get non-zero coefficients for reference
coef_df <- data.frame(
  gene_id = rownames(coef_sparse)[-1],
  coefficient = coef_sparse[-1, 1],
  stringsAsFactors = FALSE
) %>%
  filter(coefficient != 0) %>%
  arrange(desc(abs(coefficient)))

cat(sprintf("  Genes with non-zero coefficients: %d\n", nrow(coef_df)))

# Create sample summary
sample_summary <- data.frame(
  sample_id = c(r0_tumor_ids, r1_tumor_ids),
  group = c(rep("R0", length(r0_tumor_ids)), rep("R1", length(r1_tumor_ids))),
  p_hat = p_hat[c(r0_tumor_ids, r1_tumor_ids)],
  stringsAsFactors = FALSE
)

sample_summary$is_r0_like <- sample_summary$p_hat <= theta
sample_summary$qc_status <- ifelse(
  sample_summary$group == "R0", "R0 (reference)",
  ifelse(sample_summary$is_r0_like, "R1 excluded (R0-like)", "R1 retained")
)

# Add case info: extract case_submitter_id from sample_id
# Sample ID format: SC080541_merged -> case_submitter_id: SC080541
sample_summary$case_submitter_id <- gsub("_merged$", "", sample_summary$sample_id)

# Join to get POC from ret_cases
if ("poc" %in% colnames(ret_cases)) {
  poc_df <- ret_cases %>% dplyr::select(case_submitter_id, poc)
  sample_summary <- sample_summary %>%
    left_join(poc_df, by = "case_submitter_id")
} else if ("POC" %in% colnames(ret_cases)) {
  poc_df <- ret_cases %>% dplyr::select(case_submitter_id, POC) %>%
    dplyr::rename(poc = POC)
  sample_summary <- sample_summary %>%
    left_join(poc_df, by = "case_submitter_id")
} else {
  sample_summary$poc <- NA_real_
}

# Compile all results
qc_results <- list(
  # Configuration
  config = CONFIG,
  
  
  # glmnet results
  glmnet = list(
    cv_fit = cv_fit,
    selected_lambda = selected_lambda,
    coefficients = coef_df,
    n_nonzero = nonzero_coef
  ),
  
  
  # P_hat values
  p_hat = list(
    all = p_hat,
    r0 = p_hat_r0,
    r1 = p_hat_r1,
    threshold = theta
  ),
  
  
  # Sample classification
  samples = list(
    r0_tumor_ids = r0_tumor_ids,
    r1_tumor_ids = r1_tumor_ids,
    r0_like_ids = r0_like_ids,
    retained_r1_ids = retained_r1_ids,
    summary = sample_summary
  ),
  
  # Input data reference
  input = list(
    n_degs = length(common_genes),
    deg_gene_ids = common_genes,
    sign_alignment = pi_signs
  ),
  
  # Timestamp
  timestamp = Sys.time()
)

# ============================================================================
# 9. Save results
# ============================================================================

cat("\n--- 9. Saving results ---\n")

output_path <- paste0(paths$processed, "reo_glmnet_qc_results.rds")
saveRDS(qc_results, output_path)
cat(sprintf("  Results saved: %s\n", output_path))

# Save sample summary as CSV
csv_path <- paste0(paths$output, "reo_glmnet_qc_samples.csv")
write.csv(sample_summary, csv_path, row.names = FALSE)
cat(sprintf("  Sample summary CSV: %s\n", csv_path))

# Save coefficients as CSV
if (nrow(coef_df) > 0) {
  coef_csv_path <- paste0(paths$output, "reo_glmnet_coefficients.csv")
  write.csv(coef_df, coef_csv_path, row.names = FALSE)
  cat(sprintf("  Coefficients CSV: %s\n", coef_csv_path))
}

# ============================================================================
# 10. Summary
# ============================================================================

cat("\n")
cat("=======================================================================\n")
cat("  Phase 1 Complete: Sample QC with glmnet\n")
cat("=======================================================================\n")

cat("\nSummary:\n")
cat(sprintf("  Input DEGs: %d\n", length(common_genes)))
cat(sprintf("  glmnet non-zero coefficients: %d\n", nonzero_coef))
cat(sprintf("  R0 samples: %d (all retained as reference)\n", length(r0_tumor_ids)))
cat(sprintf("  R1 samples: %d total\n", length(r1_tumor_ids)))
cat(sprintf("    - Excluded (R0-like): %d\n", length(r0_like_ids)))
cat(sprintf("    - Retained: %d\n", length(retained_r1_ids)))
cat(sprintf("  Exclusion rate: %.1f%%\n", 
            length(r0_like_ids) / length(r1_tumor_ids) * 100))

cat("\nThreshold:\n")
cat(sprintf("  R0 %.0f%% percentile P_hat = %.3f\n", 
            CONFIG$R0LIKE_QUANTILE * 100, theta))

cat("\nNext step: Run 12_reo_pair_selection.R\n")

# Clean up
rm(list = setdiff(ls(), c("paths", "qc_results")))
gc()

cat("\nPhase 1 completed successfully!\n")